# Configuration for labeler action
# https://github.com/actions/labeler

# Models
models:
  - changed-files:
    - any-glob-to-any-file: 'src/msgflux/models/**'

# Core
core:
  - changed-files:
    - any-glob-to-any-file:
      - 'src/msgflux/generation/**'
      - 'src/msgflux/dsl/**'
      - 'src/msgflux/nn/**'

# Tests
tests:
  - changed-files:
    - any-glob-to-any-file: 'tests/**'

# Documentation
documentation:
  - changed-files:
    - any-glob-to-any-file:
      - '**/*.md'
      - 'docs/**'

# CI/CD
ci:
  - changed-files:
    - any-glob-to-any-file:
      - '.github/workflows/**'
      - '.github/dependabot.yml'
      - '.github/labeler.yml'

# Dependencies
dependencies:
  - changed-files:
    - any-glob-to-any-file:
      - 'pyproject.toml'
      - 'uv.lock'
      - '.pre-commit-config.yaml'

# Examples
examples:
  - changed-files:
    - any-glob-to-any-file: 'examples/**'
