name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'

categories:
  - title: 'Breaking Changes'
    labels:
      - 'breaking-change'
      - 'breaking'
  - title: 'Features'
    labels:
      - 'enhancement'
      - 'feat'
      - 'feature'
  - title: 'Bug Fixes'
    labels:
      - 'bug'
      - 'fix'
  - title: 'Performance'
    labels:
      - 'performance'
      - 'perf'
  - title: 'Security'
    labels:
      - 'security'
  - title: 'Documentation'
    labels:
      - 'documentation'
      - 'docs'
  - title: 'CI/CD'
    labels:
      - 'ci'
      - 'ci-cd'
  - title: 'Dependencies'
    labels:
      - 'dependencies'
  - title: 'Maintenance'
    labels:
      - 'maintenance'
      - 'chore'
      - 'refactor'
      - 'refactoring'
      - 'tests'
      - 'test'

change-template: '- $TITLE by @$AUTHOR in #$NUMBER'
change-title-escapes: '\<*_&'

version-resolver:
  major:
    labels:
      - 'breaking-change'
      - 'major'
  minor:
    labels:
      - 'enhancement'
      - 'feat'
      - 'feature'
  patch:
    labels:
      - 'bug'
      - 'fix'
      - 'patch'
      - 'documentation'
      - 'ci'
      - 'dependencies'
      - 'maintenance'
      - 'chore'
      - 'refactor'
      - 'tests'
  default: patch

template: |
  ## Summary

  $CHANGES

  ## Contributors

  $CONTRIBUTORS
